// <auto-generated />
using System;
using DepoYonetimSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DepoYonetimSistemi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251222225329_littleChange")]
    partial class littleChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DepoYonetimSistemi.Models.Cpu", b =>
                {
                    b.Property<int>("CpuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CpuId"));

                    b.Property<double>("BaseClockGHz")
                        .HasColumnType("float");

                    b.Property<double?>("BoostClockGHz")
                        .HasColumnType("float");

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Threads")
                        .HasColumnType("int");

                    b.HasKey("CpuId");

                    b.ToTable("Cpus");

                    b.HasData(
                        new
                        {
                            CpuId = 1,
                            BaseClockGHz = 2.5,
                            BoostClockGHz = 4.4000000000000004,
                            Cores = 6,
                            Manufacturer = "Intel",
                            Model = "Core i5-12400F",
                            Threads = 12
                        },
                        new
                        {
                            CpuId = 2,
                            BaseClockGHz = 3.7000000000000002,
                            BoostClockGHz = 4.5999999999999996,
                            Cores = 6,
                            Manufacturer = "AMD",
                            Model = "Ryzen 5 5600X",
                            Threads = 12
                        });
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.Gpu", b =>
                {
                    b.Property<int>("GpuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GpuId"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Memory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GpuId");

                    b.ToTable("Gpus");

                    b.HasData(
                        new
                        {
                            GpuId = 1,
                            Manufacturer = "NVIDIA",
                            Memory = "12GB GDDR6",
                            Model = "RTX 3060"
                        },
                        new
                        {
                            GpuId = 2,
                            Manufacturer = "AMD",
                            Memory = "8GB GDDR6",
                            Model = "RX 6600 XT"
                        });
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Aisle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shelf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Aisle = "A",
                            Bin = "01",
                            Shelf = "1"
                        },
                        new
                        {
                            LocationId = 2,
                            Aisle = "A",
                            Bin = "05",
                            Shelf = "2"
                        },
                        new
                        {
                            LocationId = 3,
                            Aisle = "B",
                            Bin = "02",
                            Shelf = "1"
                        },
                        new
                        {
                            LocationId = 4,
                            Aisle = "C",
                            Bin = "04",
                            Shelf = "3"
                        });
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("LocationId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.ProductCpu", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CpuId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CpuId");

                    b.HasIndex("CpuId");

                    b.ToTable("ProductCpus");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.ProductGpu", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("GpuId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "GpuId");

                    b.HasIndex("GpuId");

                    b.ToTable("ProductGpus");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.ProductRam", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RamId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "RamId");

                    b.HasIndex("RamId");

                    b.ToTable("ProductRams");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.ProductScreen", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ScreenId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "ScreenId");

                    b.HasIndex("ScreenId");

                    b.ToTable("ProductScreens");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.ProductStock", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<string>("SeriNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductId", "WarehouseId");

                    b.HasIndex("SeriNumber")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.ToTable("ProductStocks", t =>
                        {
                            t.HasTrigger("trg_DeleteProductWhenAllStockZero");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.ProductStorage", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("StorageId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "StorageId");

                    b.HasIndex("StorageId");

                    b.ToTable("ProductStorages");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.Ram", b =>
                {
                    b.Property<int>("RamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RamId"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SizeGB")
                        .HasColumnType("int");

                    b.Property<int?>("SpeedMHz")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RamId");

                    b.ToTable("Rams");

                    b.HasData(
                        new
                        {
                            RamId = 1,
                            Manufacturer = "Corsair",
                            Model = "Vengeance LPX",
                            SizeGB = 16,
                            SpeedMHz = 3200,
                            Type = "DDR4"
                        },
                        new
                        {
                            RamId = 2,
                            Manufacturer = "Kingston",
                            Model = "Fury Beast",
                            SizeGB = 32,
                            SpeedMHz = 3600,
                            Type = "DDR4"
                        });
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.Screen", b =>
                {
                    b.Property<int>("ScreenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScreenId"));

                    b.Property<string>("PanelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RefreshRate")
                        .HasColumnType("int");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SizeInches")
                        .HasColumnType("float");

                    b.HasKey("ScreenId");

                    b.ToTable("Screens");

                    b.HasData(
                        new
                        {
                            ScreenId = 1,
                            PanelType = "IPS",
                            RefreshRate = 60,
                            Resolution = "3840x2160",
                            SizeInches = 27.0
                        },
                        new
                        {
                            ScreenId = 2,
                            PanelType = "IPS",
                            RefreshRate = 165,
                            Resolution = "1920x1080",
                            SizeInches = 24.0
                        });
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.Storage", b =>
                {
                    b.Property<int>("StorageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StorageId"));

                    b.Property<int>("CapacityGB")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StorageId");

                    b.ToTable("Storages");

                    b.HasData(
                        new
                        {
                            StorageId = 1,
                            CapacityGB = 1000,
                            Manufacturer = "Samsung",
                            Model = "970 EVO Plus",
                            Type = "NVMe SSD"
                        },
                        new
                        {
                            StorageId = 2,
                            CapacityGB = 1000,
                            Manufacturer = "Seagate",
                            Model = "Barracuda",
                            Type = "HDD"
                        });
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SeriNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "admin",
                            Role = 0,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.WareHouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WarehouseId");

                    b.ToTable("WareHouses");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.Product", b =>
                {
                    b.HasOne("DepoYonetimSistemi.Models.Location", "Location")
                        .WithMany("Products")
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.ProductCpu", b =>
                {
                    b.HasOne("DepoYonetimSistemi.Models.Cpu", "Cpu")
                        .WithMany("ProductCpus")
                        .HasForeignKey("CpuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepoYonetimSistemi.Models.Product", "Product")
                        .WithMany("ProductCpus")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cpu");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.ProductGpu", b =>
                {
                    b.HasOne("DepoYonetimSistemi.Models.Gpu", "Gpu")
                        .WithMany("ProductGpus")
                        .HasForeignKey("GpuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepoYonetimSistemi.Models.Product", "Product")
                        .WithMany("ProductGpus")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gpu");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.ProductRam", b =>
                {
                    b.HasOne("DepoYonetimSistemi.Models.Product", "Product")
                        .WithMany("ProductRams")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepoYonetimSistemi.Models.Ram", "Ram")
                        .WithMany("ProductRams")
                        .HasForeignKey("RamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Ram");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.ProductScreen", b =>
                {
                    b.HasOne("DepoYonetimSistemi.Models.Product", "Product")
                        .WithMany("ProductScreens")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepoYonetimSistemi.Models.Screen", "Screen")
                        .WithMany("ProductScreens")
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.ProductStock", b =>
                {
                    b.HasOne("DepoYonetimSistemi.Models.Product", "Product")
                        .WithMany("ProductStocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepoYonetimSistemi.Models.WareHouse", "Warehouse")
                        .WithMany("ProductStocks")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.ProductStorage", b =>
                {
                    b.HasOne("DepoYonetimSistemi.Models.Product", "Product")
                        .WithMany("ProductStorages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepoYonetimSistemi.Models.Storage", "Storage")
                        .WithMany("ProductStorages")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.Transaction", b =>
                {
                    b.HasOne("DepoYonetimSistemi.Models.Product", "Product")
                        .WithMany("Transactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepoYonetimSistemi.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.Cpu", b =>
                {
                    b.Navigation("ProductCpus");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.Gpu", b =>
                {
                    b.Navigation("ProductGpus");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.Location", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.Product", b =>
                {
                    b.Navigation("ProductCpus");

                    b.Navigation("ProductGpus");

                    b.Navigation("ProductRams");

                    b.Navigation("ProductScreens");

                    b.Navigation("ProductStocks");

                    b.Navigation("ProductStorages");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.Ram", b =>
                {
                    b.Navigation("ProductRams");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.Screen", b =>
                {
                    b.Navigation("ProductScreens");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.Storage", b =>
                {
                    b.Navigation("ProductStorages");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.User", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("DepoYonetimSistemi.Models.WareHouse", b =>
                {
                    b.Navigation("ProductStocks");
                });
#pragma warning restore 612, 618
        }
    }
}
